### ISSUE TITLE
json parser erases file

### ISSUE THREAD

**Issue by jamesRUS52** [axibase/axibase-collector#149]
Hi, json parser deletes file even "Delete Files on Upload" option does not enable

**Comment by raipc** [comment]
@jamesRUS52 Please, could you try to update your Collector instance? Both issues should be solved in revision 20388.

**Comment by rodionos** [comment]
@jamesRUS52 - fixed in 20388

**Comment by jamesRUS52** [comment]
Thank you
It works now

**Comment by rodionos** [comment]
@jamesRUS52 - Sounds good. 

Keep in mind though that upcoming Collector updates will be compatible only with activated ATSD **SE** and **EE** editions. They will not be able to send data into ATSD **CE** instances. The CE has been EOL-ed several months ago.

You can check what type of license is installed in your ATSD instance on the **Settings > License** page.
