### ISSUE TITLE
Job: JDBC: Execution time limit

### ISSUE THREAD

**Issue by jamesRUS52** [axibase/axibase-collector#167]
Hello
I have slowly SQL query to collect data from vmware database
and job fails after about 150 seconds.
Can I disable or increase exution time limit ?

**Comment by jamesRUS52** [comment]
I have


Max Rows -1
Query Timeout, seconds -1

But it is not working

**Comment by unrealwork** [comment]
@jamesRUS52 
Hi, thanks for sharing the problem. 
Could you provide us some helpful information. 

1. How did you run the collector (pure installation/docker/etc)?
2. Export the job and attach the file.
![Screenshot(6)](https://user-images.githubusercontent.com/2435006/95558848-8c5b7500-0a1f-11eb-9afb-7c1e9a1d96b9.png)
3. Reporoduce the problem and attach log file. [link](https://axibase.com/docs/axibase-collector/logging.html)

**Comment by jamesRUS52** [comment]
I increased timeout limits on datasource settings
It works now.
